upstream ml_servers {
    server ml-container-blue:8000 weight=9; 
    server ml-container-green:8000 weight=1; 
}

server {
    listen 80; # Nginx слушает внутри на 80 порту
    location / {
        proxy_pass http://ml_servers;
    }
}