name: Model Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          # Сборка образа API
          docker build -t ghcr.io/${{ github.repository_owner }}/ml-app:latest .
          
          # Авторизация в хранилище GitHub (пароль подставляется сам)
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Отправка образа в облако
          docker push ghcr.io/${{ github.repository_owner }}/ml-app:latest